TRUNCATE TABLE person_spouse CASCADE;

TRUNCATE TABLE person_parent CASCADE;

TRUNCATE TABLE person_child CASCADE;

TRUNCATE TABLE usr CASCADE;

TRUNCATE TABLE gedcom CASCADE;

TRUNCATE TABLE person CASCADE;